### ISSUE TITLE
Action returns success, but nothing appears in JIRA

### ISSUE THREAD

**Issue by mfanto** [reload/github-security-jira#19]
First let me say thank you for building this. It's perfect for what I'm trying to achieve. 

I have set up a GitHub Action based on the README. It seems like the action always returns success, even if I use an invalid token. 

I've been unable to get any issue to show up within JIRA. It could be that I have an invalid config, but, unfortunately with everything returning success, I can't debug it. 

Please let me know if there's any debug information I can provide!

**Comment by arnested** [comment]
Hi @mfanto,

Sorry for letting you stay in the dark. We've been really busy lately so none of us involved in this has had them time to look into this.

Did you ever figure out what the problem was?

If the command succeeds no matter what happens I think we should indeed build in some more logging and error messages.

**Comment by arnested** [comment]
Hi @mfanto,

Another observation. From the README: 

> A secret called `GitHubSecurityToken` which should contain a [Personal Access Token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) for the GitHub user under which this action should be executed. The token must include the `public_repo` scope if checking only public repos, or the `repo` scope for use on private repos. Also, the user must have [access to security alerts in the repo](https://help.github.com/en/github/managing-security-vulnerabilities/managing-alerts-for-vulnerable-dependencies-in-your-organization).

The last part _Also, the user must have [access to security alerts in the repo](https://help.github.com/en/github/managing-security-vulnerabilities/managing-alerts-for-vulnerable-dependencies-in-your-organization)_.

If this is not the case I think the result will be that everything just succeeds without any issues being created.

This is because the GraphQL lookup the action does just returns no results.

**Comment by arnested** [comment]
I'm closing this due to lack of response. Feel free to reopen.
