### ISSUE TITLE
 Debug output Issue

### ISSUE THREAD

**Issue by shahmanthan1209** [reload/github-security-jira#43]
>  Set up jobs
>  Build Sample-account-github-jira/Todo-Application@master27s
>  Run GraphQL query against GH 4.x API
>  Debug output

/home/runner/work/_temp/314346d0-a25a-49d5-870d-07e31135af9a.sh: line 137: syntax error near unexpected token `('
##[error]Process completed with exit code 2.

Could you please share some light on this fix?

**Comment by arnested** [comment]
Could you share your workflow file?

**Comment by shahmanthan1209** [comment]
Sure. Here's the thing:

name: GitHub Security Alerts for Jira
on:
  push
jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: Sample-account-github-jira/Todo-Application@master
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://**.atlassian.net
          JIRA_USER: **
          JIRA_PROJECT: PROJ
          JIRA_ISSUE_TYPE: Security
          JIRA_WATCHERS: **

**Comment by arnested** [comment]
A guess: you don't have an issue type named "Security" in Jira.

Try "Bug" or "Story" or some other existing issue type. 

"Security" is a custom issue type we created. The example should probably use something more standard.

**Comment by shahmanthan1209** [comment]
I am afraid I have created issue type as "Security" manually. 
I am creating workflow file inside the corresponding github repo. Should I need to configure any other thing?
<img width="1263" alt="Screen Shot 2020-07-09 at 4 20 14 PM" src="https://user-images.githubusercontent.com/20572973/87086808-149f6380-c200-11ea-8903-18a32a732151.png">

**Comment by shahmanthan1209** [comment]
I am not sure why path looks like -> home/runner/work/Todo-Application/Todo-Application in the last line before getting the error.

**Comment by arnested** [comment]
The problem you run into is because when you copied the files needed for the action you missed the "execute bit" on the `bin/ghsec-jira`.

At least that's the problem in this comment: https://github.com/reload/github-security-jira/issues/43#issuecomment-656332049. 
 The initial problem you describe was something different.

The recommended way to use the action is to refer to our action instead of copying parts our action to your own repo:
```
        uses: reload/github-security-jira@v1.x
```
When you copy the files to your own repo it becomes difficult for us to help you and it becomes harder for you to maintain.

**Comment by shahmanthan1209** [comment]
Could you please mention where to specify executebit inside ghsec-jira file?

Also, I tried your repo under "uses" tab and it gives me below error:
Error Message : {"errorMessages":[],"errors":{"commentLevel":"Role with id:  
   Developers does not exist."}} - JiraClient.php line 264:

**Comment by arnested** [comment]
The execute bit is not inside the file. It's the Unix/Linux file permissions: https://wiki.archlinux.org/index.php/File_permissions_and_attributes

The error you get is because of a "hidden/undocumented feature": when an issue is created a comment will be posted on the issue. That comment will be restricted to the "Developers" role in Jira. I guess you don't have such a role.

We should make the role/comment optional (and document it).

**Comment by shahmanthan1209** [comment]
Thank you so much for your help and prompt response. I am afraid I am not able to find Dev role in .php file in src folder. Could you please guide me?

**Comment by arnested** [comment]
It's inside the reload/jira-security-issue dependency in composer.json.

I'll try to have fix for it ready in a couple of days.

**Comment by shahmanthan1209** [comment]
Thank you so much.

**Comment by arnested** [comment]
@shahmanthan1209, this should be fixed now.

Add the `JIRA_RESTRICTED_COMMENT_ROLE` environment variable and configure it with an existing role from your Jira.
